
services:
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PW}
      - POSTGRES_DB=${POSTGRES_DB} #optional (specify default database instead of $POSTGRES_DB)
    ports:
      - "5432:5432"
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    

  server1:
    restart: on-failure
    build: 
      context: ../server
      args:
        DB_NAME: "${POSTGRES_DB}"
        DB_USER: "${POSTGRES_USER}"
        DB_PASSWORD: "${POSTGRES_PW}"
    hostname: server1
    ports:
      - '81:5000'
    depends_on:
      postgres:
        condition: service_healthy

  nginx:
    build: ../nginx
    ports:
    - '80:80'
    depends_on:
    - server1


