services:
  db:
    image: 'postgres:latest'
    restart: always
    environment:
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_USER: "${DB_USER}"
  nginx:
    restart: always
    build: ../nginx
    ports:
      - '80:80'
    depends_on:
      - server1
  server1:
    build: ../server
    environment:
      - DB_HOST=db
      - DB_PASSWORD="${DB_PASSWORD}"
      - DB_USER="${DB_USER}"
      - DB_NAME="${DB_NAME}"
      - DB_PORT=5432