version: '3'
services:
  db:
    image: 'postgres:latest'
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U ${DB_USER} -d ${DB_NAME}'"]
      interval: 10s
      timeout: 3s
      retries: 3
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
  nginx:
    restart: always
    build: ../nginx
    ports:
      - '80:80'
    depends_on:
      - api
  api:
    build: ../server
    depends_on:
      db: 
        condition: service_healthy
    env_file:
    - .env