version: '3'
services:
  db:
    image: 'postgres:latest'
    restart: always
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
  nginx:
    restart: always
    build: ../nginx
    ports:
      - '80:80'
    depends_on:
      - api
  api:
    build: ../server
    depends_on:
      db: 
        condition: service_healthy
    env_file:
    - .env