version: '3.9'
services:
  db-server:
    image: 'postgres:latest'
    restart: always
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
  nginx:
    restart: always
    build: ../nginx
    ports:
      - '80:80'
  api:
    build: ../server
    depends_on:
      db-server:
        condition: service_healthy
    env_file:
    - .env
    environment:
      - PORT=5000
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db-server/${DB_NAME}?schema=public
    command: sh -c "npx prisma db push && npm run start"